### ISSUE TITLE
Is still updated for kirby 3.9.4?

### ISSUE THREAD

**Issue by Reluma** [tristantbg/kirby-shopify#18]
Hi,

Hello, sorry for bothering you, I'm trying to connect Kirby CMS to Shopify using your plugin but I'm having several issues, probably I'm doing something wrong. Has it been tested for version 3.9.4? Also, I'm not sure if I've entered the correct data in the .env file because the Shopify interface has changed now.

![Immagine 2023-05-11 170524](https://github.com/tristantbg/kirby-shopify/assets/6823205/305e7480-f4f0-4003-8015-b61441d1d7fa)
![Immagine 2023-05-11 165551](https://github.com/tristantbg/kirby-shopify/assets/6823205/d97565d4-b3ba-4535-99d0-60cf98978d2f)

as you can see from the sceenshot it seems to me that the admin API access token is useless.

Nothing is displayed in frontend.
The error in the products page (backend) is:
"The section "products" could not be loaded: collection(): Return value must be of type ?Kirby\Cms\Collection, ShopifyProductsPage returned"

I can't understand what causes this problem, if it depends on a connection error in shopify or a problem with kirby cms. I'm a little confused

thanks for your time

**Comment by tristantbg** [comment]
Hi @Reluma ,
Indeed... Shopify has changed a few things.
I have updated the readme !
The plugin should still work with the last version of Kirby.

**Comment by Reluma** [comment]
Thanks @tristantbg but there is still something wrong.
You marked useless API secret key in the screeshot and "ACCESS_TOKEN= 4 (Useless)" in the example.

They are both useless?

My problem still remains the same...

<img width="515" alt="Immagine 2023-05-16 103326" src="https://github.com/tristantbg/kirby-shopify/assets/6823205/7f46c4a3-eff1-47f1-8b53-316ef0dcda1e">

**Comment by vernone** [comment]
Hey @Reluma, did you manage to find a solution with this problem ? I'm stuck with the same issue.
